CREATE TABLE branch
(
    branch_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    building_name VARCHAR(255)                            NOT NULL,
    street        VARCHAR(255),
    city          VARCHAR(255),
    state         VARCHAR(255),
    zipcode       VARCHAR(255)                            NOT NULL,
    country       VARCHAR(255),
    phone_number  VARCHAR(255),
    email         VARCHAR(255),
    version       BIGINT                                  NOT NULL,
    CONSTRAINT pk_branch PRIMARY KEY (branch_id)
);



CREATE TABLE address
(
    address_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    building_name        VARCHAR(255),
    street               VARCHAR(255),
    city                 VARCHAR(255),
    state                VARCHAR(255),
    zipcode              VARCHAR(255),
    country              VARCHAR(255),
    address_type         SMALLINT,
    contact_phone_number VARCHAR(255),
    version              BIGINT                                  NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (address_id)
);



CREATE TABLE department
(
    dept_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dept_name    VARCHAR(255)                            NOT NULL,
    dept_head_id BIGINT,
    created_on   date,
    is_active    BOOLEAN,
    deleted      BOOLEAN                                 NOT NULL,
    branch_id    BIGINT                                  NOT NULL,
    version      BIGINT                                  NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (dept_id)
);


CREATE TABLE employee
(
    employee_id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name              VARCHAR(255)                            NOT NULL,
    middle_name             VARCHAR(255),
    last_name               VARCHAR(255)                            NOT NULL,
    date_of_birth           date                                    NOT NULL,
    employee_join_date      date,
    dept_id                 BIGINT,
    role                    VARCHAR(255),
    yearly_bonus_percentage DOUBLE PRECISION,
    salary                  DOUBLE PRECISION,
    reporting_manager_id    BIGINT,
    personal_address_id     BIGINT,
    exit_date               TIMESTAMP WITHOUT TIME ZONE,
    branch_id               BIGINT,
    version                 BIGINT                                  NOT NULL,
    CONSTRAINT pk_employee PRIMARY KEY (employee_id)
);



CREATE TABLE monthly_salary_meta
(
    id                    BIGINT NOT NULL,
    employee_employee_id  BIGINT NOT NULL,
    transaction_timestamp TIMESTAMP WITHOUT TIME ZONE,
    salary_amount         DOUBLE PRECISION,
    bonus_amount          DOUBLE PRECISION,
    total_amount          DOUBLE PRECISION,
    year_month            date,
    total_hours_worked    INTEGER,
    version               BIGINT,
    CONSTRAINT pk_monthlysalarymeta PRIMARY KEY (id)
);



-- ALTER BRANCH
ALTER TABLE branch ADD CONSTRAINT uc_branch_email UNIQUE (email);
ALTER TABLE branch ADD CONSTRAINT uc_branch_phone_number UNIQUE (phone_number);
ALTER TABLE branch ADD CONSTRAINT uc_branch_zipcode UNIQUE (zipcode);


-- ALTER EMPLOYEE
ALTER TABLE employee ADD CONSTRAINT uc_employee_personal_address UNIQUE (personal_address_id);
ALTER TABLE employee ADD CONSTRAINT FK_EMPLOYEE_ON_BRANCH FOREIGN KEY (branch_id) REFERENCES branch (branch_id);
ALTER TABLE employee ADD CONSTRAINT FK_EMPLOYEE_ON_DEPT FOREIGN KEY (dept_id) REFERENCES department (dept_id);
ALTER TABLE employee ADD CONSTRAINT FK_EMPLOYEE_ON_PERSONAL_ADDRESS FOREIGN KEY (personal_address_id) REFERENCES address (address_id);
ALTER TABLE employee ADD CONSTRAINT FK_EMPLOYEE_ON_REPORTING_MANAGER FOREIGN KEY (reporting_manager_id) REFERENCES employee (employee_id);


-- ALTER DEPARTMENT
ALTER TABLE department ADD CONSTRAINT FK_DEPARTMENT_ON_DEPT_HEAD FOREIGN KEY (dept_head_id) REFERENCES employee (employee_id);
ALTER TABLE department ADD CONSTRAINT uc_department_dept_head UNIQUE (dept_head_id);
ALTER TABLE department ADD CONSTRAINT unqiue_dept_per_branch UNIQUE (branch_id, dept_name);
ALTER TABLE department ADD CONSTRAINT FK_DEPARTMENT_ON_BRANCH FOREIGN KEY (branch_id) REFERENCES branch (branch_id);


-- ALTER MONTHLY_SALARY_META
ALTER TABLE monthly_salary_meta ADD CONSTRAINT FK_MONTHLYSALARYMETA_ON_EMPLOYEE_EMPLOYEE FOREIGN KEY (employee_employee_id) REFERENCES employee (employee_id);


